apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  initContainers:
  - name: init-myservice
    image: busybox
    command: ['sh','-c','until nslookup nginxservice; do echo waiting for nginxsservice; sleep 2; done']
  containers:
  - name: myapp-nginx
    image: nginx

