apiVersion: v1
kind: Pod
metadata:
  name: myapp-init-pod
  labels:
    app: myinitapp
spec:
  initContainers:
  - name: init-myservice
    image: busybox
    command: ['sh','-c','until nslookup nginxservice; do echo waiting for nginxsservice; sleep 2; done']
  containers:
  - name: myapp-init-nginx
    image: nginx

