apiVersion: v1
kind: Service
metadata:
  name: nginx-service-2
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
  - protocol: TCP
    type: NodePort
    # service端口
    port: 8081      
    # pod 端口 
    targetPort: 80  
    