# 创建 Service
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-2
spec:
  # Serivce的类型，默认是 ClusteroIP，使用NodePort可以通过节点Node的IP访问服务
  type: NodePort
  # 下游的Pod选择
  selector:
    app: myapp
  # 对外暴露的端口
  ports:
  - protocol: TCP
    type: NodePort
    # service端口
    port: 8081      
    # pod 端口 
    targetPort: 80  
    