apiVersion: v1
kind: Service
metadata:
  name: nginxservice-deploy
spec:
  type: NodePort
  selector:
    app: nginx-deploy
  ports:
  - protocol: TCP
    # service端口
    port: 9090  
    # pod 端口 
    targetPort: 80  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx-deploy
  replicas: 5
  template:
    metadata:
      labels:
        app: nginx-deploy
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
    