# secret类似于configMap, 只不过 secret的配置值需要经过 base64编码
apiVersion: v1
kind: Secret
metadata:
  name: dotfile-secret
data:
  .secret-file: UGxlYXNlIFN0YXIgTXkgQ29kZSwgTm90IENvbXBsZXRlIG9uIE5leHQh
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-dotfiles-pod
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: dotfile-secret
  containers:
    - name: dotfile-test-container
      image: registry.k8s.io/busybox
      command:
        - cat 
        - "/etc/secret-volume/.secret-file"
      # 引用 secrt 的方式类似于 configMap
      volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/etc/secret-volume"