apiVersion: v1
kind: Service
metadata:
  name: nginxservice_deploy
spec:
  type: NodePort
  selector:
    app: nginx-deploy
  ports:
  - protocol: TCP
    # service端口
    port: 8080      
    # pod 端口 
    targetPort: 80  
    