apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm
data:
  default.conf: |
   server {
    listen 80;
    listen [::]:80;
    server_name localhost;
    location / {
      root /usr/share/nginx/html/;
      index index.html indx.htm;
    }

    location /app {
      root /usr/share/nginx/html/apps;
      index index.html indx.htm;
    }
   }